name: Docker

on:
  push:
    branches:
      - base

env:
  IMAGE_NAME: pylerplate

jobs:
  push:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    strategy:
        matrix:
          image:
            - compile
            - runtime
          python:
            - 3.8
            - 3.9
    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: docker build . --build-arg PYTHON_VERSION=${{ matrix.python }} --file Dockerfile.${{ matrix.image }} --tag $IMAGE_NAME

      - name: Log into GitHub Container Registry
        run: echo "${{ secrets.CR_PAT }}" | docker login https://ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push image to GitHub Container Registry
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME
          VERSION="$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')-${{ matrix.image}}-${{ matrix.python }}"

          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION

          docker tag $IMAGE_NAME $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$VERSION
